### ISSUE TITLE
[Request] Detect dead links in pages

### ISSUE THREAD

**Issue by xplshn** [thecsw/darkness#8]
This snippet here allows you to detect dead links in your pages, thought it may be useful here, I use it on my page, here's the src: https://fatbuffalo.neocities.org/def/js/detect_dead_links.js

Here's my page (made with Hugo, but another one with more personality is underway): https://fatbuffalo.neocities.org/def/

**Comment by thecsw** [comment]
hi, I'm seeing the script is calling `https://corsproxy.org/` for checking the link status and I'd rather avoid making any 3rd party calls unless absolutely necessary. dead links is actually OK on a page, just shows that internet develops and parts of it die. thanks for your issue

**Comment by xplshn** [comment]
understood
