### ISSUE TITLE
CSS and favicon are misplaced

### ISSUE THREAD

**Issue by e-eight** [thecsw/darkness#9]
When I use the latest version of darkness (`go install github.com/thecsw/darkness@latest`) to create Ishmael, it places the link to the `css` file between `</head>` and `<body>`. And the favicon is also missing.

**Comment by thecsw** [comment]
hi! it seems `@latest` was pointing to some **SUPER** old commit. I refreshed the cache of the go proxy, so it should go through, as the `new` command should create a colorful output like 

<img width="426" alt="Screenshot 2024-05-05 at 12 32 28 AM" src="https://github.com/thecsw/darkness/assets/16922860/9f57e40e-7872-4b42-be88-74bd4e5dafc7">

so the html output will be present as follows

<img width="1058" alt="Screenshot 2024-05-05 at 12 31 27 AM" src="https://github.com/thecsw/darkness/assets/16922860/b0b33fb7-2968-40af-9296-45388571fd63">

if it still doesn't work, install from git or commit `0ad4206`

**Comment by e-eight** [comment]
Thanks!
